from pathlib import Path
import json,re,hashlib,math,subprocess,ast
ROOT=Path(r'C:\Users\xmz_r\Downloads\flooow-v042-implementation')
E=ROOT/'docs/evidence/package-0090-g3f4-full-binding-enforcement-qualification'
S=ROOT/'scripts/validation/package_0090_full_qualification'
def write(name,obj):(E/name).write_bytes((json.dumps(obj,indent=2)+'\n').encode())
rounds={}
for p in sorted(E.rglob('RAW-QUALIFICATION.json')):
    rounds[p.parent.relative_to(E).as_posix()]=json.loads(p.read_text())
def cases(groups):return [{'round':r,**c} for r,d in rounds.items() for c in d['cases'] if c['group'] in groups]
def matrix(name,groups,limitations):write(name,{'scope':'TEST_ONLY_NONCANONICAL','cases':cases(groups),'limitations':limitations,'overlapping_rounds_are_not_unique_coverage':True})
latest=E/'attempt08'; context=json.loads((latest/'SYNTHETIC-PUBLIC-CONTEXT.json').read_text())
write('FULL-SYNTHETIC-BINDING-MATRIX.json',{**json.loads((latest/'FULL-SYNTHETIC-BINDING-MATRIX.json').read_text()),'runtime_cases':cases(['binding']),'disposition':'PASS_STRUCTURE_38_TAGS_40_COLUMNS; HOLD_FULL_FROZEN_PARITY_AND_NUMERIC_POLICY_VALIDATION','not_required':[{'field':'new_database_uuid','classification':'NOT_REQUIRED','reason':'Database identity is server OID/name in enrollment; no invented canonical database UUID'},{'field':'standalone_manifest_revoked_flag','classification':'NOT_REQUIRED','reason':'Current signer key/authority, window and external custody govern denial'}]})
matrix('ATTESTATION-QUALIFICATION.json',['attestation'],'Pinned original bundle and actual crypto material association; synthetic OpenSSL verification. Full frozen S02/JVM/economic-source/accepted-proof parity remains HOLD. Historical failed substitution witness is retained.')
matrix('APPROVAL-CUSTODY-MATRIX.json',['custody'],'Root-owned external current status and exact artifact/target commitment. PASS_DISPOSABLE only; canonical current custody not consumed.')
matrix('ROLE-SLOT-ADMISSION-MATRIX.json',['admission'],'OID/name recognition and final exact identity tested; actual allocator OID reuse and normative tombstone lifecycle remain HOLD.')
matrix('TEXT-ENCODING-QUALIFICATION.json',['encoding'],'237 native parser checks in BUILD records: strict UTF8/NFC via qualified existing ICU76; unsupported ICU denies. NFC unmanaged name confers no governed authority. No normalization rewrite.')
logs={r:(E/r/'NATIVE-RUNTIME.log').read_text() for r in rounds if (E/r/'NATIVE-RUNTIME.log').exists()}
restoration={r:{'preserved_yes':len(re.findall('TIMEOUT_RESTORATION preserved=YES custom_active=NO',l)),'preserved_no':len(re.findall('TIMEOUT_RESTORATION preserved=NO',l))} for r,l in logs.items()}
write('TIMEOUT-RESTORATION-PROOF.json',{'cases':cases(['timeout']),'native_snapshots':restoration,'mechanism':'Dedicated USER_TIMEOUT with PG_TRY/PG_CATCH cleanup; no STATEMENT_TIMEOUT replacement. Accepted path compares SIGALRM handler/flags/mask, caller statement timer activity/deadline and inactive custom timer; idle ITIMER_REAL restoration checked. Denied backends exit; later fresh sessions tested.','limitations':'No exhaustive proof over every PostgreSQL extension-installed timer or handler. Recorded paths only.'})
events=[]
for r,l in logs.items():
    for line in l.splitlines():
        if line.startswith('{'):
            try:ev=json.loads(line)
            except ValueError:continue
            events.append({'round':r,**ev})
write('CONTINUOUS-COVERAGE-PROOF.json',{'state_records':events,'cases':cases(['enforcement','drain','restart']),'registry_identity':'Full request tuple retained with kernel pidfd; catalog PID used only for corroboration, never signal selection.','coverage':'HOLD_COMPLETE_ENROLLED_BACKEND_COVERAGE','gaps':['Pending login before SCM transfer lacks supervisor-held backend anchor. No independent exhaustive census-to-registry proof.','Serial catalog queries can delay other observation/admission; finite experimental query budget is not a universal health bound.','Supervisor loss coarse postmaster shutdown also affects unmanaged sessions; selective isolation is proved for policy revocation only.']})
matrix('INDEPENDENT-HEALTH-PROOF.json',['health','custody','enforcement'],'Backend/receiver cannot write root custody/gate or service SQL governance. Root observer alone supplies expiring experimental monotonic observation. Health lease5s is NOT policy.')
matrix('ACTIVE-ENFORCEMENT-MATRIX.json',['enforcement'],'Retained-anchor SIGINT then SIGTERM, kernel death plus fresh exact-session catalog disappearance. Selective unrelated-session witness for revocation; full supervisor/postmaster loss is coarse stack shutdown.')
write('DRAIN-STATE-MACHINE.json',{'states':['NORMAL','DENY_NEW_ADMISSION','QUARANTINE','DRAINING','DRAINED','RECONCILIATION_REQUIRED'],'cases':cases(['drain','enforcement']),'events':[e for e in events if e.get('event') in ['QUARANTINE','DRAINING','DRAINED','RECONCILIATION_REQUIRED','kernel_death']],'rules':['Unresolved live quarantine blocks new admission even after CURRENT custody returns.','DRAINED means kernel death plus authoritative catalog absence, never absence of effects.','Catalog unavailable or signals failing retains quarantine/reconciliation.','No process-control path updates or releases domain ownership.'],'full_domain_reconciliation':'HOLD'})
matrix('AMBIGUOUS-EFFECT-MATRIX.json',['effect'],'Authoritative synthetic writer quiescence/query-first demonstrated; no automatic replay. COMMIT response is deliberately discarded by harness, not a precisely synchronized real network loss. Full normative transaction/effect boundary matrix remains HOLD.')
write('OWNERSHIP-RECONCILIATION-MATRIX.json',{'cases':cases(['effect']),'ownership_retained':'PASS_SYNTHETIC_OWNED_ROW','terminal_ownership':'NOT_RUN_WITH_REASON: complete V043 claim/attempt/execution/domain wrappers not installed/executed','new_attempt_and_replay':'No automatic attempt/replay performed; normative recovery/terminal criteria remain HOLD','process_death_does_not_release':True})
matrix('CLONE-RESTORE-MATRIX.json',['clone'],'Actual logical dump/restore denies governed login on new DB identity; cold physical PGDATA copy denies startup without mandatory external inherited bootstrap. External context/artifact copies alone deny. Hostile trusted root administrator is outside threat model.')
write('RESTART-MATRIX.json',{'cases':cases(['restart']),'generation_graph':[e for e in events if e.get('event')=='receiver_armed'],'survive':['synthetic deployment/incarnation/header identity','durable effect/ownership rows'],'rotate':['atomic supervisor/receiver/postmaster anchors on stack restart','joint ephemeral epoch on receiver/postmaster/supervisor loss','backend pidfd on backend restart'],'failure_preserved':'attempt03 supervisor self pidfd CLOEXEC/descriptor reuse; fixed by explicit inheritance plus socketpair peer pidfd comparison, regression passed in attempts06/07/08'})
faults='wrong_role wrong_OID wrong_role_name wrong_attributes wrong_membership wrong_DB wrong_slot missing_binding duplicate_binding wrong_deployment wrong_incarnation revoked_approval retired_approval stale_approval tampered_approval wrong_attestation tampered_attestation wrong_signer wrong_policy_digest generation_mismatch receiver_crash supervisor_crash postmaster_restart socket_absent socket_substitution pidfd_replay stale_backend late_ACK lost_ACK partial_frame oversized_frame invalid_encoding catalog_stall watchdog_stale watchdog_unavailable cancel_failure terminate_failure ambiguous_COMMIT clone restore'.split()
mapping={'wrong_role':['role_rename'],'wrong_OID':['role_recreation'],'wrong_role_name':['role_rename'],'wrong_attributes':['attributes'],'wrong_membership':['membership'],'wrong_DB':['actual_logical_restore'],'wrong_slot':['field_identity_slots'],'missing_binding':['zero_binding'],'duplicate_binding':['duplicate_slot'],'wrong_deployment':['field_deployment_id'],'wrong_incarnation':['field_deployment_incarnation_id'],'revoked_approval':['REVOKED'],'retired_approval':['RETIRED'],'stale_approval':['STALE'],'tampered_approval':['DIGEST_MISMATCH'],'wrong_attestation':['wrong_manifest'],'tampered_attestation':['material_substitution','cryptographic_tamper'],'wrong_signer':['wrong_signer'],'wrong_policy_digest':['field_deadline_policy_digest'],'receiver_crash':['receiver_crash_during_login'],'supervisor_crash':['supervisor_restart_regression','final_receiver_supervisor_restart'],'postmaster_restart':['postmaster_database_stack_rebootstrap'],'late_ACK':['delay-ack'],'lost_ACK':['drop-ack'],'partial_frame':['partial-frame'],'catalog_stall':['catalog-stall','SPI_lock_stall'],'watchdog_stale':['independent_observer_unavailable'],'watchdog_unavailable':['independent_observer_unavailable'],'cancel_failure':['cancel_failure_then_terminate'],'terminate_failure':['terminate_failure_quarantine'],'ambiguous_COMMIT':['commit_response_lost'],'clone':['actual_physical_clone'],'restore':['actual_logical_restore']}
allcases=[{'round':r,**c} for r,d in rounds.items() for c in d['cases']]
rows=[]
for f in faults:
    refs=[c for c in allcases if any(k in c['name'] for k in mapping.get(f,[])) and c['result'].startswith('PASS')]
    rows.append({'fault':f,'result':'PASS_HANDLED' if refs else 'NOT_RUN_WITH_REASON','evidence':[{'round':c['round'],'case':c['name'],'result':c['result']} for c in refs],'reason':None if refs else 'Complete successor runtime case not established. Prior kernel/native/parser results remain preserved separately; no invented successor PASS.'})
write('FAULT-MATRIX.json',{'faults':rows,'historical_failures':[c for c in allcases if c['result']=='FAIL'],'remaining_cases':[c for c in allcases if c['result']=='NOT_RUN_WITH_REASON'],'scope':'TEST_ONLY_NONCANONICAL'})
def dist(v,fail=0,censored=0):
    v=sorted(v);return {'N':len(v),'FAIL':fail,'CENSORED':censored,**{k:(v[math.ceil(len(v)*p)-1] if v else None) for k,p in [('P50',.5),('P95',.95),('P99',.99)]},'MAX':v[-1] if v else None}
timing={'units':'microseconds','percentiles':'nearest rank; descriptive only, low N does not establish tails','rounds':{},'unknown_metrics':{k:{'N':0,'FAIL':None,'CENSORED':None,'P50':None,'P95':None,'P99':None,'MAX':None,'reason':'Required boundary not independently instrumented; not inferred zero'} for k in ['revocation_to_deny_new','revocation_to_active_detection','detection_to_cancel','quarantine_transition','full_drain_completion','cold_startup','receiver_recovery','supervisor_recovery','postmaster_rebootstrap']}}
for r,d in rounds.items():
    accepted=[e for e in events if e['round']==r and e.get('event')=='ACCEPT'];l=logs.get(r,'');obs=d['observations']
    gaps=[(b['start_ns']-a['end_ns'])/1000 for a,b in zip(obs,obs[1:])]
    timing['rounds'][r]={'native_accepted_handler_total':dist([int(v) for v in re.findall(r'ENROLLMENT_ACCEPT[^\n]*total_us=(\d+)',l)]),'receiver_accepted_reply_offsets':dist([e['reply_us'] for e in accepted]),'observer_execution':dist([(o['end_ns']-o['start_ns'])/1000 for o in obs],sum(not o['eligible'] for o in obs)),'observer_gap_including_deliberate_pauses':dist(gaps),'client_scenario_elapsed':[c for c in d['cases'] if isinstance(c.get('detail'),dict) and 'elapsed_us' in c['detail']]}
write('TIMING-MEASUREMENTS.json',timing)
matrix('LOAD-OVERLAP-PROOF.json',['load'],'Bounded workload wrapper active before/after each measured cohort request; host monotonic orchestration times. CPU quota1, memory768MiB. I/O is tmpfs writes, not physical disk/storage-tail qualification. Four requests per cohort, no numeric adoption.')
old=json.loads((ROOT/'docs/evidence/package-0090-g3f4-current-contract-reconciliation/CONTRACT-LINEAGE.json').read_text())['source_worktree_sha256']
assert all(hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in old.items())
assert not subprocess.check_output(['git','diff','--name-only'],cwd=ROOT,text=True).strip()
assert not subprocess.check_output(['docker','ps','-a','--filter','label=flooow.scope=0090-full-binding-enforcement','--format','{{.ID}}'],text=True).strip()
assert all(d.get('private_key_absent') and d.get('owned_container_removed') for d in rounds.values())
write('CANONICAL-NON-MUTATION-PROOF.json',{'scope_guard':'Owned image/label/network-none/no-mount container inspection at start; exact owned ID before removal. All SQL/crypto/fault/cleanup targets constant owned container. No canonical connection.','canonical_v6_accessed':False,'canonical_v6_mutated':False,'canonical_database_mutated':False,'canonical_ids_used':False,'canonical_header_changed':False,'canonical_readiness_changed':False,'production_secret_used':False,'T0_consumed':False,'canonical_key_generated':False,'canonical_SIGN_executed':False,'canonical_ADMIN_executed':False,'TREG_executed':False,'final_runner_executed':False,'test_only_key_generated':True,'test_only_signing_executed':True,'synthetic_fixture_admin_sql_executed':True,'historical_worktree_hashes_equal':len(old),'predecessor_tracked_changes':[],'owned_containers_remaining':[],'all_private_keys_erased_and_owned_containers_removed':True,'numbers_adopted':False})
summary={r:{'PASS':sum(c['result'].startswith('PASS') for c in d['cases']),'FAIL':sum(c['result']=='FAIL' for c in d['cases']),'NOT_RUN':sum(c['result']=='NOT_RUN_WITH_REASON' for c in d['cases']),'harness_errors':len(d['errors']),'cleaned':d.get('owned_container_removed')} for r,d in rounds.items()}
write('ROUND-SUMMARY.json',{'rounds':summary,'do_not_sum_overlapping_rounds_as_unique_coverage':True})
for p in S.glob('*.py'):ast.parse(p.read_text())
write('SOURCE-AND-BINARY-HASHES.json',{'rounds':{r:{'source_hashes':d['source_hashes'],'binary_hashes':d['binary_hashes'],'snapshot':r+'/SOURCE.json' if (E/r/'SOURCE.json').exists() else 'NOT_RETAINED_CONTENT; exact source hashes retained in raw record'} for r,d in rounds.items()},'python_syntax':'PASS'})
print(json.dumps(summary,indent=2))
